### ISSUE TITLE
Returns "Bad Username or Password" when I'm using the correct username and password.

### ISSUE THREAD

**Issue by DanielThePear** [ctrezevant/PyEdsby#11]
Hello!
I'm trying to run the example code provided here: https://github.com/ctrezevant/PyEdsby/wiki/Getting-Started
(Yes, I did replace the placeholders with the proper host, username, and password).
However, when it tries to log in, I get a "Bad Username or Password" error.
Traceback reports that the `studentData` dict returned by `sendAuthenticationData` (Line 192 of the module) contains an error 1003.
I am somewhat of a programming noob, so while I haven't been able to find the exact cause of this problem, I believe that it lies within `getauthData`, `sendAuthenticationData`, or `parseInstanceMetadata`.
Any help would be greatly appreciated.

**Comment by chtzvt** [comment]
Hey Daniel, 

Thanks for reaching out. Unfortunately, I have now ceased maintenance of the PyEdsby library for several years at this point, mostly due to the fact that I no longer have access to an Edsby instance (and thus, no personal need for the library). It is partly for this reason that I won't be able to help you personally, as I have no way to know changes have occurred to the backend since I had last been actively developing the project roughly 4 years ago.

At this time, PyEdsby is seeking contributors and maintainers. It's been orphaned! The last person to reach out with an interest in this role was @thatmich, and I'd be more than happy to bring additional contributors onto the team. I periodically receive requests to fix this bug, so I know that PyEdsby is still in demand and that people would still stand to benefit from it :)

Again, I'm sorry that I'm unable to help you further. If anything believe the time has come to pass the torch to another maintainer. You can try to triage the bug if you're up to it, otherwise it seems like we'll be waiting for an enterprising contributor to come along and tackle it for good...

Best regards and many thanks,
Charlton
